[[language]]
name = "vue"
language-servers = ["volar"]
file-types = ["vue"]
scope = "source.vue"
injection-regex = "vue"
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
file-types = ["ts", "tsx"]
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
file-types = ["js", "jsx"]
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
